tasks_api:
    type: rest
    resource: Taskul\TaskBundle\Controller\TasksRestController
    name_prefix: api_

files_tasks_api:
    type: rest
    parent:   tasks_api
    name_prefix: api_
    resource: Taskul\TaskBundle\Controller\FilesRestController

tags_tasks_api:
    type:     rest
    name_prefix: api_
    resource: Taskul\TaskBundle\Controller\TagsRestController

periods_tasks_api:
    type: rest
    parent:   tasks_api
    name_prefix: api_
    resource: Taskul\TaskBundle\Controller\PeriodRestController
