tasks_api:
    type: rest
    resource: Taskul\TaskBundle\Controller\TasksRestController
    name_prefix: api_
    defaults: { _format: html }

files_tasks_api:
    type: rest
    parent:   tasks_api
    name_prefix: api_
    resource: Taskul\TaskBundle\Controller\FilesRestController
    defaults: { _format: json }

periods_tasks_api:
    type: rest
    parent:   tasks_api
    name_prefix: api_
    resource: Taskul\TaskBundle\Controller\PeriodRestController
