<?php

namespace Taskul\TaskBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
	    public function findTasks($user)
    {
        return $this->getEntityManager($user)
            ->createQuery('SELECT t FROM TaskBundle:Task t WHERE t.owner = :user or :user MEMBER OF t.members')
            ->setParameter('user', $user->getId())
            ->getResult();
    }
}
