imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "FOSCommentBundle", "TaskBundle", "FileBundle", "MainBundle", "FriendBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/nodejs]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        types:
            TaskStatusType: Taskul\TaskBundle\DBAL\Types\TaskStatusType


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: public
    user_class: Taskul\UserBundle\Entity\User
    from_email:
        address: me@example.com
        sender_name: Example
    registration:
        confirmation:
            enabled: false
        form:
            type: taskul_user_registration
    resetting:
        form:
             type: taskul_user_resetting

fos_facebook:
    #file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias:  facebook
    app_id: 433353293400449
    secret: 83dfc9e8a8b14b568a2ff545ff654313
    cookie: true
    permissions: [email, user_birthday, user_location]

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: "MainBundle:Menu:main.html.twig"
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
    providers:
        builder_alias: false    # enable the builder-based provider
        container_aware: true # disable default

fos_comment:
    db_driver: orm
    acl: true
    service:
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
        markup: markup.exercise_html_purifier
    class:
        model:
            comment: Taskul\CommentBundle\Entity\Comment
            thread: Taskul\CommentBundle\Entity\Thread
            vote: Taskul\CommentBundle\Entity\Vote

fos_message:
    db_driver: orm
    thread_class: Taskul\MessageBundle\Entity\Thread
    message_class: Taskul\MessageBundle\Entity\Message

fpn_tag:
    model:
        tag_class:     Taskul\TagBundle\Entity\Tag
        tagging_class: Taskul\TagBundle\Entity\Tagging

apy_breadcrumb_trail:
    template: MainBundle::breadcrumbtrail.html.twig

fos_js_routing:
    routes_to_expose:
        - "^api_.*" # expose all routes with a name starting with api_

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB

jms_serializer:
  metadata:
    auto_detection: true
    directories:
      FOSUserBundle:
        namespace_prefix: "FOS\\UserBundle"
        path: "@UserBundle/Resources/config/serializer/fos"

fos_rest:
    format_listener:
        default_priorities: [ html, 'json', '*/*']
        fallback_format: json
        prefer_extension: false

spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:  Taskul\TimelineBundle\Entity\Timeline
                action:    Taskul\TimelineBundle\Entity\Action
                component: Taskul\TimelineBundle\Entity\Component
                action_component: Taskul\TimelineBundle\Entity\ActionComponent
    notifiers:
        - spy_timeline.unread_notifications
    render:
        path:     'TimelineBundle:Timeline'
        fallback: 'TimelineBundle:Timeline:default.html.twig'
        #i18n: #Do you want to use i18n when rendering ? if not, remove this not.
            #fallback: en