imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        save_path: "%kernel.root_dir%/sessions/"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        locales: [es, en]

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "FOSCommentBundle", "TaskBundle", "FileBundle", "MainBundle", "FriendBundle", "MessageBundle", "UserBundle" ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        sass:    ~
        compass: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        coffee:
            bin: /usr/local/lib/node_modules/coffee-script/bin/coffee
            node: /usr/bin/nodejs
            apply_to: "\.coffee$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        types:
            TaskStatusType: Taskul\TaskBundle\DBAL\Types\TaskStatusType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: public
    user_class: Taskul\UserBundle\Entity\User
    group:
        group_class:  Taskul\UserBundle\Entity\Group
    from_email:
        address: camilocot@gmail.com
        sender_name: Taskul.net
    registration:
        confirmation:
            enabled: false
        form:
            type: taskul_user_registration
    resetting:
        form:
            type: taskul_user_resetting
    profile:
        form:
            type: taskul_user_profile

fos_facebook:
    alias:  facebook
    app_id: 433353293400449
    secret: 83dfc9e8a8b14b568a2ff545ff654313
    cookie: true
    permissions: [email, user_birthday, user_location]

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: "MainBundle:Menu:main.html.twig"
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
    providers:
        builder_alias: false    # enable the builder-based provider
        container_aware: true # disable default

fos_comment:
    db_driver: orm
    acl: true
    service:
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
        acl:
            thread:  fos_comment.acl.thread.security
            comment: fos_comment.acl.comment.security
            vote:    taskul_comment.acl.vote.security
        markup: markup.exercise_html_purifier
    class:
        model:
            comment: Taskul\CommentBundle\Entity\Comment
            thread: Taskul\CommentBundle\Entity\Thread
            vote: Taskul\CommentBundle\Entity\Vote

fos_message:
    db_driver: orm
    thread_class: Taskul\MessageBundle\Entity\Thread
    message_class: Taskul\MessageBundle\Entity\Message
    new_thread_form:
        type:               taskul_message.new_thread_form.type

apy_breadcrumb_trail:
    template: MainBundle::breadcrumbtrail.html.twig

fos_js_routing:
    routes_to_expose:
        - "^es__RG__api_.*"
        - "^en__RG__api_.*"
        - api_count_task_list_status
        - api_get_tags
        - api_list_task_status

jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB

jms_serializer:
  metadata:
    auto_detection: true
    directories:
      FOSUserBundle:
        namespace_prefix: "FOS\\UserBundle"
        path: "@UserBundle/Resources/config/serializer/fos"

fos_rest:
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
    routing_loader:
        default_format: json

spy_timeline:
    drivers:
        orm:
            object_manager: doctrine.orm.entity_manager
            classes:
                query_builder: ~ # Spy\TimelineBundle\Driver\ORM\QueryBuilder\QueryBuilder
                timeline:  Taskul\TimelineBundle\Entity\Timeline
                action:    Taskul\TimelineBundle\Entity\Action
                component: Taskul\TimelineBundle\Entity\Component
                action_component: Taskul\TimelineBundle\Entity\ActionComponent
    filters:
        duplicate_key:
            priority: 10
        data_hydrator:
            priority: 20
            filter_unresolved: true
            locators:
                - spy_timeline.filter.data_hydrator.locator.doctrine_orm
    notifiers:
        - taskul_timeline.unread_notifications
    render:
        path:     'TimelineBundle:Timeline/verbs'
        fallback: 'TimelineBundle:Timeline:default.html.twig'
        resources:
            - 'TimelineBundle:Timeline:components.html.twig'
        i18n:
            fallback: es
ornicar_gravatar: ~
ornicar_akismet:
    api_key:        8bc2c0d9bb02
    url:            http://www.taskul.net

jms_i18n_routing:
    default_locale: %locale%
    locales: [es, en]
    strategy: prefix

ornicar_apc:
    host: http://www.taskul.net
    web_dir: %kernel.root_dir%/../web
    mode: curl

fm_bbcode:
    filter_sets:
        my_comment_filter:
            locale: %locale%
            xhtml: true
            filters: [ default, block, code, email, list, quote, text, url ]
            hooks: [ emoticon, censor, clickable ]
        my_description_filter:
            locale: %locale%
            xhtml: true
            filters: [ default, block, code, email, image, list, quote, text, url, video ]
            hooks: [ emoticon, clickable ]
        my_message_filter:
            locale: %locale%
            xhtml: true
            filters: [ default, block, code, email, image, list, quote, text, url, video ]
            hooks: [ emoticon, censor, clickable ]
