taskul_comment:
    resource: "@TaskulCommentBundle/Controller/"
    type:     annotation
    prefix:   /

friend:
    resource: "@FriendBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

# message:
#     resource: "@MessageBundle/Controller/"
#     type:     annotation
#     prefix:   /

tasks:
    type: rest
    resource: "@TaskBundle/Resources/config/tasks_routes.yml"
    prefix: /api

files:
    resource: "@FileBundle/Controller/"
    type:     annotation
    prefix:   /api

tags:
    type: rest
    prefix: /api
    resource: "@TagBundle/Resources/config/tags_routes.yml"

user:
    resource: "@UserBundle/Controller/"
    type: annotation
    prefix: /

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@TaskulCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /msg

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
