# app/config/routing.yml

timeline:
    resource: "@TimelineBundle/Controller/"
    type:     annotation
    prefix:   /

friend:
    resource: "@FriendBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    resource: "@MainBundle/Controller/"
    type:     annotation
    prefix:   /

tasks:
    type: rest
    resource: "@TaskBundle/Resources/config/tasks_routes.yml"
    prefix: /api

default:
    resource: "@TaskBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /tasks

files:
    resource: "@FileBundle/Controller/"
    type:     annotation
    prefix:   /api

tags:
    type: rest
    prefix: /api
    resource: "@TagBundle/Resources/config/tags_routes.yml"

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@TaskulCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

fos_message:
    resource: "@MessageBundle/Resources/config/routing.yml"
    prefix: /msg

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"



