jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    acl:
        connection: default
    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
            id: my.facebook.user
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public:
            # since anonymous is allowed users will not be forced to login
            pattern: ^/.*
            fos_facebook:
                app_url: "http://apps.facebook.com/eventstagram/"
                server_url: "http://taskul.local/app_dev.php"
                login_path: fos_user_security_login
                check_path: fos_facebook_security_check
                default_target_path: /
                provider: my_fos_facebook_provider
                success_handler: taskul.user.handler.authentication_handler
                failure_handler: taskul.user.handler.authentication_handler
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: taskul.user.handler.authentication_handler
                failure_handler: taskul.user.handler.authentication_handler
            anonymous: true
            logout: true
        login:
            pattern: ^/login$
            security: false

        # main:
        #     pattern: ^/
        #     form_login:
        #         csrf_provider: form.csrf_provider
        #     fos_facebook:
        #         app_url: "http://apps.facebook.com/taskulnet/"
        #         server_url: "http://fosfacebook.local.com/facebookApp"
        #         login_path: /login
        #         check_path: /loginFacebook
        #         provider: my_fos_facebook_provider
        #         default_target_path: /
        #     logout:       true
        #     anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/frequest/, role: ROLE_USER }
        - { path: ^/task/, role: ROLE_USER }
        - { path: ^/friend/, role: ROLE_USER }
        - { path: ^/api/, role: ROLE_USER }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
