security:
    acl:
        connection: default
    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
            id: my.facebook.user

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public:
            # since anonymous is allowed users will not be forced to login
            pattern: ^/.*
            fos_facebook:
                app_url: "http://apps.facebook.com/eventstagram/"
                server_url: "http://taskul.local/app_dev.php"
                login_path: fos_user_security_login
                check_path: fos_facebook_security_check
                default_target_path: /
                provider: my_fos_facebook_provider
                success_handler: taskul.user.handler.authentication_handler
                failure_handler: taskul.user.handler.authentication_handler
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: taskul.user.handler.authentication_handler
                failure_handler: taskul.user.handler.authentication_handler
            anonymous: true
            logout:
                invalidate_session: false
                path: fos_user_security_logout
        login:
            pattern: ^/login$
            security: false

    access_control:
        - { path: ^/(es|en)/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Admin login page needs to be access without credential
        - { path: ^/(es|en)/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/admin/, role: ROLE_ADMIN }
        - { path: ^/(es|en)/frequest/, role: ROLE_USER }
        - { path: ^/(es|en)/task/, role: ROLE_USER }
        - { path: ^/(es|en)/tasks, role: ROLE_USER }
        - { path: ^/(es|en)/friend/, role: ROLE_USER }
        - { path: ^/(es|en)/api/, role: ROLE_USER }
        - { path: ^/(es|en)/msg/, role: ROLE_USER }
        - { path: ^/(es|en)/dashboard, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
